mainloop_glib.c File Reference
Example for main loop using glib 2.
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <sys/time.h>
#include <sys/socket.h>
#include <signal.h>
#include <fcntl.h>
#include `glib.h`
Data Structures
struct listen_source_t
listen source state
struct echo_source_t
echo source state
struct chargen_source_t
chargen source state
struct source_t
Defines
#define PORT_ECHO 5005
tcp port to listen for echo clients
#define PORT_CHARGEN 5006
tcp port to listen for chargen clients
#define HEARTBEAT_INTERVAL 2
heartbeat interval (in seconds)
#define SLOWHEARTBEAT_INTERVAL 15
slow heartbeat interval (in seconds)
#define BUFSIZE 16
buffer size for echo client
#define MSG_HEARTBEAT 0
#define MSG_SLOWHEARTBEAT 1
#define MSG_MAINLOOP 2
#define MSG_ACCEPT 3
#define MSG_TOOMANY 4
#define MSG_CLOSE 5
#define MSG_READ 6
#define MSG_WRITE 7
#define MSG_FULL 8
#define MSG_EMPTY 9
Typedefs
typedef GSource *(* getclientsourcefunc)()
Functions
void message (int msg)
print message describing current activity
int listensocket (int port)
return tcp socket listening on port specified
void setnonblock (int fd)
set a file descriptor to be nonblocking
source_t * listensource (getclientsourcefunc getclientsource, int port)
construct listensource listening on port specified
GSource * getechoclientsource ()
construct GSourceFuncs for echo client
GSource * getchargenclientsource ()
construct GSourceFuncs for chargen client
gboolean heartbeat (gpointer data)
print heartbeat message
gboolean slowheartbeat (gpointer data)
print `slowheartbeat` message
gboolean check (GSource *source)
check whether source is ready for processing
void source_close (source_t *source)
close a source and dispose of source
gboolean accept_prepare (GSource *source, gint *timeout)
Prepare GSource for polling a server socket for accept.
gboolean accept_dispatch (GSource *source, GSourceFunc callback, gpointer user_data)
dispatch (process) listening socket
gboolean echo_prepare (GSource *source, gint *timeout)
Prepare GSource for polling an echo client.
gboolean echo_dispatch (GSource *source, GSourceFunc callback, gpointer user_data)
dispatch (process) echo client
void echo_dispatch_read (source_t *echosource)
read data from echo client
void echo_dispatch_write (source_t *echosource)
write data to an echo client
gboolean chargen_prepare (GSource *source, gint *timeout)
Prepare GSource for polling an chargen client.
gboolean chargen_dispatch (GSource *source, GSourceFunc callback, gpointer user_data)
dispatch (process) chargen client
void blocksigpipe ()
block SIGPIPE
int main ()
Variables
char chargen_buf [] = `0123456789abcdefghijklmnopqrstuv`
characters to return in chargen service
Detailed Description
Example for main loop using glib 2.
Author: Rico Pajarola
This example uses glib 2 for handling events.
Definition in file mainloop_glib.c.
Define Documentation
#define BUFSIZE 16
buffer size for echo client
Definition at line 35 of file mainloop_glib.c.
#define HEARTBEAT_INTERVAL 2
heartbeat interval (in seconds)
Definition at line 29 of file mainloop_glib.c.
#define MSG_ACCEPT 3
Definition at line 40 of file mainloop_glib.c.
#define MSG_CLOSE 5
Definition at line 42 of file mainloop_glib.c.
#define MSG_EMPTY 9
Definition at line 46 of file mainloop_glib.c.
#define MSG_FULL 8
Definition at line 45 of file mainloop_glib.c.
#define MSG_HEARTBEAT 0
Definition at line 37 of file mainloop_glib.c.
#define MSG_MAINLOOP 2
Definition at line 39 of file mainloop_glib.c.
#define MSG_READ 6
Definition at line 43 of file mainloop_glib.c.
#define MSG_SLOWHEARTBEAT 1
Definition at line 38 of file mainloop_glib.c.
#define MSG_TOOMANY 4
Definition at line 41 of file mainloop_glib.c.
#define MSG_WRITE 7
Definition at line 44 of file mainloop_glib.c.
#define PORT_CHARGEN 5006
tcp port to listen for chargen clients
Definition at line 26 of file mainloop_glib.c.
#define PORT_ECHO 5005
tcp port to listen for echo clients
Definition at line 23 of file mainloop_glib.c.
#define SLOWHEARTBEAT_INTERVAL 15
slow heartbeat interval (in seconds)
Definition at line 32 of file mainloop_glib.c.
Typedef Documentation
typedef GSource*(* getclientsourcefunc)()
Definition at line 51 of file mainloop_glib.c.
Function Documentation
gboolean accept_dispatch (GSource * gsource, GSourceFunc callback, gpointer user_data) [static]
dispatch (process) listening socket
Parameters:
gsource source to process
callback callback function (unused)
user_data I have absolutely no idea how to use this... nice idea though
Returns: always TRUE
Definition at line 347 of file mainloop_glib.c.
References listen_source_t::getclientsource, source_t::listen, message(), MSG_ACCEPT, source_t::pollfd, and setnonblock().
Referenced by listensource().
349 {
350     struct sockaddr_in sain;
351     int             fd;
352     socklen_t       t;
353     source_t       *source;
354     source_t       *clientsource;
355 
356     source = (source_t *) gsource;
357 
358     if (source->pollfd.revents & (G_IO_HUP | G_IO_ERR)) {
359         perror("accept_dispatch()");
360         exit(EXIT_FAILURE);
361     }
362 
363     /* accept new connection */
364     t = sizeof(sain);
365     if ((fd = accept(source->pollfd.fd, (void *) &sain, &t)) == -1) {
366         if (errno == EWOULDBLOCK) {
367             return TRUE;
368         }
369         perror("accept(ECHO)");
370         exit(EXIT_FAILURE);
371     }
372     setnonblock(fd);
373     message(MSG_ACCEPT);
374 
375     clientsource = (source_t *) source->listen.getclientsource();
376     clientsource->pollfd.fd = fd;
377     g_source_add_poll((GSource *) clientsource, &(clientsource->pollfd));
378     clientsource->id =
379         g_source_attach((GSource *) clientsource,
380                         g_source_get_context((GSource *) clientsource));
381     return TRUE;
382 }
gboolean accept_prepare (GSource * source, gint * timeout) [static]
Prepare GSource for polling a server socket for accept.
Parameters:
source GSource to prepare
timeout maximum timeout to set for poll() (out)
Returns: always FALSE (use poll)
Definition at line 326 of file mainloop_glib.c.
References source_t::pollfd.
Referenced by listensource().
327 {
328     source_t       *xsource;
329 
330     xsource = (source_t *) source;
331 
332     xsource->pollfd.events = G_IO_IN;
333     *timeout = -1;              /* no timeout */
334     return FALSE;
335 }
void blocksigpipe (void) [static]
block SIGPIPE
Trying to write to a socket when the other end has already closed the connection results in SIGPIPE. Not usefull in this context.
Definition at line 170 of file mainloop_glib.c.
Referenced by main().
171 {
172     struct sigaction act;
173 
174     act.sa_handler = SIG_IGN;
175     sigemptyset(&act.sa_mask);
176     act.sa_flags = SA_RESTART;
177     if (sigaction(SIGPIPE, &act, NULL) == -1) {
178         perror("sigaction(SIGPIPE, <ignore>)");
179         exit(EXIT_FAILURE);
180     }
181 }
gboolean chargen_dispatch (GSource * source, GSourceFunc callback, gpointer user_data) [static]
dispatch (process) chargen client
Parameters:
source source to process
callback callback function (unused)
user_data ?
Returns: always TRUE
there is no chargen_dispatch_write, writing is done directly in chargen_dispatch
Definition at line 633 of file mainloop_glib.c.
References source_t::chargen, chargen_buf, chargen_source_t::i, message(), MSG_WRITE, source_t::pollfd, and source_close().
Referenced by getchargenclientsource().
635 {
636     ssize_t         nwrite;
637     source_t       *chargensource;
638 
639     chargensource = (source_t *) source;
640 
641     nwrite =
642         write(chargensource->pollfd.fd,
643               chargen_buf + chargensource->chargen.i,
644               sizeof(chargen_buf) - chargensource->chargen.i);
645     switch (nwrite) {
646     case -1:
647         if (errno == EPIPE) {
648             source_close((source_t *) chargensource);
649             return TRUE;
650         } else if ((errno != EINTR) && (errno != EWOULDBLOCK)) {
651             perror("write()");
652             exit(EXIT_FAILURE);
653         }
654         break;
655     case 0:
656         break;
657     default:
658         message(MSG_WRITE);
659         chargensource->chargen.i += nwrite;
660         chargensource->chargen.i %= sizeof(chargen_buf);
661     }
662     return TRUE;
663 }
gboolean chargen_prepare (GSource * source, gint * timeout) [static]
Prepare GSource for polling an chargen client.
Parameters:
source GSource to prepare
timeout maximum timeout to set for poll() (out)
Returns: always FALSE (use poll)
Definition at line 609 of file mainloop_glib.c.
References source_t::pollfd.
Referenced by getchargenclientsource().
610 {
611     source_t       *chargensource;
612 
613     chargensource = (source_t *) source;
614 
615     chargensource->pollfd.events = G_IO_OUT;
616 
617     return FALSE;
618 }
gboolean check (GSource * source) [static]
check whether source is ready for processing
Parameters:
source GSource to check
Returns: TRUE if resource is ready
Definition at line 307 of file mainloop_glib.c.
References source_t::pollfd.
Referenced by getchargenclientsource(), getechoclientsource(), and listensource().
308 {
309 
310     source_t       *xsource;
311 
312     xsource = (source_t *) source;
313 
314     return xsource->pollfd.revents ? TRUE : FALSE;
315 }
gboolean echo_dispatch (GSource * source, GSourceFunc callback, gpointer user_data) [static]
dispatch (process) echo client
Parameters:
source source to process
callback callback function (unused)
user_data ?
Returns: always TRUE
Definition at line 471 of file mainloop_glib.c.
References echo_dispatch_read(), echo_dispatch_write(), source_t::pollfd, and source_close().
Referenced by getechoclientsource().
472 {
473     source_t       *echosource;
474 
475     echosource = (source_t *) source;
476 
477     if (echosource->pollfd.revents & (G_IO_HUP | G_IO_ERR)) {
478         source_close((source_t *) echosource);
479     }
480     if (echosource->pollfd.revents & G_IO_IN) {
481         echo_dispatch_read(echosource);
482     }
483     if (echosource->pollfd.revents & G_IO_OUT) {
484         echo_dispatch_write(echosource);
485     }
486     return TRUE;
487 }
void echo_dispatch_read (source_t * echosource) [static]
read data from echo client
Parameters:
echosource echo client source
If the buffer is not full, tries to do one read from the filedescriptor associated with this echo client.
Definition at line 498 of file mainloop_glib.c.
References echo_source_t::buf, BUFSIZE, source_t::echo, message(), MSG_FULL, MSG_READ, echo_source_t::n, source_t::pollfd, echo_source_t::r, source_close(), and echo_source_t::w.
Referenced by echo_dispatch().
499 {
500     ssize_t         nread;
501 
502     if (echosource->echo.n == BUFSIZE) {
503         message(MSG_FULL);
504         return;
505     }
506 
507     if (echosource->echo.r >= echosource->echo.w) {
508         nread =
509             read(echosource->pollfd.fd,
510                  echosource->echo.buf + echosource->echo.r,
511                  BUFSIZE - echosource->echo.r);
512     } else {
513         nread =
514             read(echosource->pollfd.fd,
515                  echosource->echo.buf + echosource->echo.r,
516                  echosource->echo.w - echosource->echo.r);
517     }
518 
519     switch (nread) {
520     case -1:
521         if ((errno != EINTR) && (errno != EWOULDBLOCK)) {
522             perror("read()");
523             exit(EXIT_FAILURE);
524         }
525         break;
526     case 0:
527         source_close((source_t *) echosource);
528         return;
529     default:
530         message(MSG_READ);
531         echosource->echo.n += nread;
532         echosource->echo.r += nread;
533         echosource->echo.r %= BUFSIZE;
534     }
535 }
void echo_dispatch_write (source_t * echosource) [static]
write data to an echo client
Parameters:
echosource echo client source
If the buffer is not empty, tries to do one write to the filedescriptor associated with the echo client.
Definition at line 546 of file mainloop_glib.c.
References echo_source_t::buf, BUFSIZE, source_t::echo, message(), MSG_EMPTY, MSG_WRITE, echo_source_t::n, source_t::pollfd, echo_source_t::r, source_close(), and echo_source_t::w.
Referenced by echo_dispatch().
547 {
548     ssize_t         nwrite;
549 
550     if (echosource->echo.n == 0) {
551         message(MSG_EMPTY);
552         return;
553     }
554 
555     if (echosource->echo.r > echosource->echo.w) {
556         nwrite =
557             write(echosource->pollfd.fd,
558                   echosource->echo.buf + echosource->echo.w,
559                   echosource->echo.r - echosource->echo.w);
560     } else {
561         nwrite =
562             write(echosource->pollfd.fd,
563                   echosource->echo.buf + echosource->echo.w,
564                   BUFSIZE - echosource->echo.w);
565     }
566 
567     switch (nwrite) {
568     case -1:
569         if (errno == EPIPE) {
570             source_close((source_t *) echosource);
571         } else if ((errno != EINTR) && (errno != EWOULDBLOCK)) {
572             perror("write()");
573             exit(EXIT_FAILURE);
574         }
575         break;
576     case 0:
577         break;
578     default:
579         message(MSG_WRITE);
580         echosource->echo.n -= nwrite;
581         echosource->echo.w += nwrite;
582         echosource->echo.w %= BUFSIZE;
583     }
584 }
gboolean echo_prepare (GSource * source, gint * timeout) [static]
Prepare GSource for polling an echo client.
Parameters:
source GSource to prepare
timeout maximum timeout to set for poll() (out)
Returns: always FALSE (use poll)
If the buffer is full, checking for read is turned off resp. if the buffer is empty, checking for write is turned off.
Definition at line 442 of file mainloop_glib.c.
References BUFSIZE, source_t::echo, echo_source_t::n, and source_t::pollfd.
Referenced by getechoclientsource().
443 {
444     source_t       *echosource;
445 
446     echosource = (source_t *) source;
447 
448     switch (echosource->echo.n) {
449     case 0:
450         echosource->pollfd.events = G_IO_IN;
451         break;
452     case BUFSIZE:
453         echosource->pollfd.events = G_IO_OUT;
454         break;
455     default:
456         echosource->pollfd.events = G_IO_IN | G_IO_OUT;
457     }
458     return FALSE;
459 }
GSource * getchargenclientsource () [static]
construct GSourceFuncs for chargen client
Returns: GSource for chargen client
Definition at line 414 of file mainloop_glib.c.
References source_t::chargen, chargen_dispatch(), chargen_prepare(), check(), and chargen_source_t::i.
Referenced by main().
415 {
416     static GSourceFuncs funcs = { NULL, NULL, NULL, NULL, NULL, NULL };
417     source_t       *chargensource;
418 
419     /* cannot reference functions in static initializer */
420     funcs.prepare = chargen_prepare;
421     funcs.check = check;
422     funcs.dispatch = chargen_dispatch;
423     funcs.finalize = NULL;
424 
425     chargensource = (source_t *) g_source_new(&funcs, sizeof(source_t));
426     chargensource->chargen.i = 0;
427     return (GSource *) chargensource;
428 }
GSource * getechoclientsource () [static]
construct GSourceFuncs for echo client
Returns: GSource for echo client
Definition at line 390 of file mainloop_glib.c.
References check(), source_t::echo, echo_dispatch(), echo_prepare(), echo_source_t::n, echo_source_t::r, and echo_source_t::w.
Referenced by main().
391 {
392     static GSourceFuncs funcs = { NULL, NULL, NULL, NULL, NULL, NULL };
393     source_t       *echosource;
394 
395     /* cannot reference functions in static initializer */
396     funcs.prepare = echo_prepare;
397     funcs.check = check;
398     funcs.dispatch = echo_dispatch;
399     funcs.finalize = NULL;
400 
401     echosource = (source_t *) g_source_new(&funcs, sizeof(source_t));
402     echosource->echo.r = 0;
403     echosource->echo.w = 0;
404     echosource->echo.n = 0;
405     return (GSource *) echosource;
406 }
gboolean heartbeat (gpointer data) [static]
print heartbeat message
Returns: always TRUE
Definition at line 281 of file mainloop_glib.c.
References message(), and MSG_HEARTBEAT.
Referenced by main().
282 {
283     message(MSG_HEARTBEAT);
284     return TRUE;
285 }
int listensocket (int port) [static]
return tcp socket listening on port specified
Parameters:
port port number in host byte order
Returns: file descriptor for listening socket
The socket is set to be nonblocking
Definition at line 193 of file mainloop_glib.c.
References setnonblock().
194 {
195     int             serverfd;
196     struct sockaddr_in sain;
197     int             one;
198 
199     /* set up tcp socket for listening */
200     sain.sin_family = AF_INET;
201     sain.sin_port = htons(port);
202     sain.sin_addr.s_addr = INADDR_ANY;
203     if ((serverfd = socket(AF_INET, SOCK_STREAM, 0)) == -1) {
204         perror("socket(AF_INET, SOCK_STREAM, 0)");
205         exit(EXIT_FAILURE);
206     }
207     one = 1;
208     if (setsockopt
209         (serverfd, SOL_SOCKET, SO_REUSEADDR, &one,
210          (int) sizeof(one)) == -1) {
211         perror("setsockopt(SO_REUSEADDR)");
212         exit(EXIT_FAILURE);
213     }
214     if (bind
215         (serverfd, (struct sockaddr *) &sain,
216          sizeof(struct sockaddr_in)) == -1) {
217         perror("bind()");
218         exit(EXIT_FAILURE);
219     }
220     if (listen(serverfd, 5) == -1) {
221         perror("listen()");
222         exit(EXIT_FAILURE);
223     }
224     setnonblock(serverfd);
225 
226     printf("listening on port %d\n", port);
227 
228     return serverfd;
229 }
source_t * listensource (getclientsourcefunc getclientsource, int port) [static]
construct listensource listening on port specified
Parameters:
getclientsource function returning clientsource for accepted connection
port tcp port to listen on in host byte order
Returns: listensource_t
Definition at line 257 of file mainloop_glib.c.
References accept_dispatch(), accept_prepare(), check(), listen_source_t::getclientsource, source_t::listen, listensocket(), listensource(), and source_t::pollfd.
Referenced by listensource(), and main().
258 {
259     static GSourceFuncs listenfuncs;
260     source_t       *listensource;
261 
262     listenfuncs.prepare = &accept_prepare;
263     listenfuncs.check = &check;
264     listenfuncs.dispatch = &accept_dispatch;
265     listenfuncs.finalize = NULL;
266     listensource =
267         (source_t *) g_source_new(&listenfuncs, sizeof(source_t));
268     listensource->listen.getclientsource = getclientsource;
269 
270     listensource->pollfd.fd = listensocket(port);
271     g_source_add_poll((GSource *) listensource, &(listensource->pollfd));
272     return listensource;
273 }
int main ()
Definition at line 666 of file mainloop_glib.c.
References blocksigpipe(), getchargenclientsource(), getechoclientsource(), heartbeat(), HEARTBEAT_INTERVAL, source_t::id, listensource(), PORT_CHARGEN, PORT_ECHO, slowheartbeat(), and SLOWHEARTBEAT_INTERVAL.
667 {
668     GMainLoop      *mainloop;
669     GMainContext   *context;
670     source_t       *listenecho, *listenchargen;
671 
672     /* check glib version */
673     if (!GLIB_CHECK_VERSION(2, 0, 0)) {
674         fprintf(stderr, "glib %d.%d.%d is too old\n", GLIB_MAJOR_VERSION,
675                 GLIB_MINOR_VERSION, GLIB_MICRO_VERSION);
676         exit(EXIT_FAILURE);
677     }
678 
679     printf("example: glib main loop\n");
680 
681     blocksigpipe();
682 
683     /* create main loop */
684     context = g_main_context_default();
685     mainloop = g_main_loop_new(context, FALSE);
686 
687     /* create echo service */
688     listenecho = listensource(getechoclientsource, PORT_ECHO);
689     listenecho->id = g_source_attach((GSource *) listenecho, context);
690 
691     /* create chargen service */
692     listenchargen = listensource(getchargenclientsource, PORT_CHARGEN);
693     listenchargen->id =
694         g_source_attach((GSource *) listenchargen, context);
695 
696     /* install heartbeat */
697     (void) g_timeout_add(1000 * HEARTBEAT_INTERVAL, &heartbeat, NULL);
698     (void) g_timeout_add(1000 * SLOWHEARTBEAT_INTERVAL, &slowheartbeat, NULL);
699     printf("heartbeat every %d seconds\n", HEARTBEAT_INTERVAL);
700     printf("slow heartbeat every %d seconds\n", SLOWHEARTBEAT_INTERVAL);
701 
702     /* run the main loop */
703     g_main_loop_run(mainloop);
704     /* notreached */
705 
706     g_main_loop_unref(mainloop);
707     exit(EXIT_SUCCESS);
708 }
void message (int msg) [static]
print message describing current activity
Parameters:
msg id of message to print (MSG_XYZ)
Definition at line 126 of file mainloop_glib.c.
References MSG_ACCEPT, MSG_CLOSE, MSG_EMPTY, MSG_FULL, MSG_HEARTBEAT, MSG_MAINLOOP, MSG_READ, MSG_SLOWHEARTBEAT, MSG_TOOMANY, and MSG_WRITE.
127 {
128     switch (msg) {
129     case MSG_HEARTBEAT:
130         printf("H");
131         break;
132     case MSG_SLOWHEARTBEAT:
133         printf("S");
134         break;
135     case MSG_MAINLOOP:
136         printf("M");
137         break;
138     case MSG_ACCEPT:
139         printf("A");
140         break;
141     case MSG_TOOMANY:
142         printf("T");
143         break;
144     case MSG_CLOSE:
145         printf("C");
146         break;
147     case MSG_READ:
148         printf("R");
149         break;
150     case MSG_WRITE:
151         printf("W");
152         break;
153     case MSG_FULL:
154         printf("F");
155         break;
156     case MSG_EMPTY:
157         printf("E");
158         break;
159     }
160     fflush(stdout);
161 }
void setnonblock (int fd) [static]
set a file descriptor to be nonblocking
Parameters:
fd file descriptor
Non-Blocking works only for Sockets, Pipes and slow devices, it has no effect when used with regular files
Definition at line 240 of file mainloop_glib.c.
241 {
242     int             flag;
243 
244     flag = fcntl(fd, F_GETFL);
245     fcntl(fd, F_GETFL, flag | O_NONBLOCK);
246 }
gboolean slowheartbeat (gpointer data) [static]
print `slowheartbeat` message
Returns: always TRUE
Definition at line 293 of file mainloop_glib.c.
References message(), and MSG_SLOWHEARTBEAT.
Referenced by main().
294 {
295     message(MSG_SLOWHEARTBEAT);
296     return TRUE;
297 }
void source_close (source_t * source) [static]
close a source and dispose of source
Parameters:
source source to close/dispose
Definition at line 592 of file mainloop_glib.c.
References source_t::id, message(), MSG_CLOSE, and source_t::pollfd.
Referenced by chargen_dispatch(), echo_dispatch(), echo_dispatch_read(), and echo_dispatch_write().
593 {
594     message(MSG_CLOSE);
595     (void) g_source_remove(source->id);
596     close(source->pollfd.fd);
597     g_source_unref((GSource *) source);
598 }
Variable Documentation
char chargen_buf[] = `0123456789abcdefghijklmnopqrstuv` [static]
characters to return in chargen service
Definition at line 49 of file mainloop_glib.c.
Referenced by chargen_dispatch().