mainloop_good.c File Reference
Example for `good` main loop.
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <sys/time.h>
#include <sys/socket.h>
#include <signal.h>
#include <fcntl.h>
Data Structures
struct echo_client_t
echo client specific state
struct chargen_client_t
chargen client specific state
struct client_t
client state
struct alarm_t
alarm handler state
Defines
#define PORT_ECHO 5005
tcp port to listen for echo clients
#define PORT_CHARGEN 5006
tcp port to listen for chargen clients
#define HEARTBEAT_INTERVAL 2
heartbeat interval (in seconds)
#define SLOWHEARTBEAT_INTERVAL 15
slow heartbeat interval (in seconds)
#define BUFSIZE 16
buffer size for echo client
#define MAXCLIENTS 8
maximum number of clients
#define MAXALARMS 8
maximum number of different alarms
#define MSG_HEARTBEAT 0
#define MSG_SLOWHEARTBEAT 1
#define MSG_MAINLOOP 2
#define MSG_ACCEPT 3
#define MSG_TOOMANY 4
#define MSG_CLOSE 5
#define MSG_READ 6
#define MSG_WRITE 7
#define MSG_FULL 8
#define MSG_EMPTY 9
#define MIN(a, b) ((a)<(b)?(a):(b))
#define MAX(a, b) ((a)>(b)?(a):(b))
Typedefs
typedef void(* eventhandler_t)(int i)
event handler
typedef void(* alarmhandler_t)(void)
alarm handler
Functions
void message (int msg)
print message describing current activity
void blocksigpipe (void)
block SIGPIPE
void initalarms (void)
install non-resetting signal handler for alarms
void addalarm (alarmhandler_t handler, long interval)
add new alarm
void checkalarms (void)
check for pending alarms and execute alarm handlers
void alarmhandler (void)
signal handler for alarms
void heartbeat (void)
print heartbeat message
void slowheartbeat (void)
print `slowheartbeat` message
int listensocket (int port)
return tcp socket listening on port specified
void setnonblock (int fd)
set a file descriptor to be nonblocking
void initclients ()
initialize client state array
void addclient (int fd, eventhandler_t read, eventhandler_t write, eventhandler_t except)
add new client
void delclient (int i)
delete client
void mainloop ()
execute one iteration of THE mainloop
void closeclient (int i)
close and delete client session
void acceptecho (int i)
accept connection and set up new session for `echo` service
void readecho (int i)
read data from echo client
void writeecho (int i)
write data to an echo client
void flowecho (int i)
do `flow` control for echo
void acceptchargen (int i)
accept connection and set up new session for `chargen` service
void writechargen (int i)
write data to an chargen client
int main ()
Variables
char chargen_buf [] = `0123456789abcdefghijklmnopqrstuv`
characters to return in chargen service
unsigned long npollfd
number of file descriptors to check
client_t clients [MAXCLIENTS]
array of client states
pollfd pollfds [MAXCLIENTS]
pollfds for poll()
alarm_t alarms [MAXALARMS]
alarms
Detailed Description
Example for `good` main loop.
Author: Rico Pajarola
This example does essentially what glib would do: events are abstracted using callbacks making the mainloop generic (but not as generic as glib). Even though it is easy to add a new input or event source, the whole mechanism is still very much tied to the structure of this program).
Definition in file mainloop_good.c.
Define Documentation
#define BUFSIZE 16
buffer size for echo client
Definition at line 37 of file mainloop_good.c.
#define HEARTBEAT_INTERVAL 2
heartbeat interval (in seconds)
Definition at line 31 of file mainloop_good.c.
#define MAX(a, b) ((a)>(b)?(a):(b))
Definition at line 57 of file mainloop_good.c.
#define MAXALARMS 8
maximum number of different alarms
Definition at line 43 of file mainloop_good.c.
Referenced by addalarm(), alarmhandler(), checkalarms(), and initalarms().
#define MAXCLIENTS 8
maximum number of clients
Definition at line 40 of file mainloop_good.c.
#define MIN(a, b) ((a)<(b)?(a):(b))
Definition at line 56 of file mainloop_good.c.
#define MSG_ACCEPT 3
Definition at line 48 of file mainloop_good.c.
#define MSG_CLOSE 5
Definition at line 50 of file mainloop_good.c.
#define MSG_EMPTY 9
Definition at line 54 of file mainloop_good.c.
#define MSG_FULL 8
Definition at line 53 of file mainloop_good.c.
#define MSG_HEARTBEAT 0
Definition at line 45 of file mainloop_good.c.
#define MSG_MAINLOOP 2
Definition at line 47 of file mainloop_good.c.
#define MSG_READ 6
Definition at line 51 of file mainloop_good.c.
#define MSG_SLOWHEARTBEAT 1
Definition at line 46 of file mainloop_good.c.
#define MSG_TOOMANY 4
Definition at line 49 of file mainloop_good.c.
#define MSG_WRITE 7
Definition at line 52 of file mainloop_good.c.
#define PORT_CHARGEN 5006
tcp port to listen for chargen clients
Definition at line 28 of file mainloop_good.c.
#define PORT_ECHO 5005
tcp port to listen for echo clients
Definition at line 25 of file mainloop_good.c.
#define SLOWHEARTBEAT_INTERVAL 15
slow heartbeat interval (in seconds)
Definition at line 34 of file mainloop_good.c.
Typedef Documentation
typedef void(* alarmhandler_t)(void)
alarm handler
Definition at line 106 of file mainloop_good.c.
typedef void(* eventhandler_t)(int i)
event handler
Parameters:
i index into clients
Definition at line 84 of file mainloop_good.c.
Function Documentation
void acceptchargen (int i) [static]
accept connection and set up new session for `chargen` service
Parameters:
i index into pollfds/clients array for server descriptor
Definition at line 680 of file mainloop_good.c.
References addclient(), clients, closeclient(), and writechargen().
Referenced by main().
681 {
682     int             fd;
683     socklen_t       t;
684     struct sockaddr_in sain;
685 
686     t = sizeof(sain);
687     if ((fd = accept(clients[i].fd, (void *) &sain, &t)) == -1) {
688         if (errno == EWOULDBLOCK) {
689             return;
690         }
691         perror("accept(CHARGEN)");
692         exit(EXIT_FAILURE);
693     }
694     addclient(fd, NULL, &writechargen, &closeclient);
695 }
void acceptecho (int i) [static]
accept connection and set up new session for `echo` service
Parameters:
i index into pollfds/clients array for server descriptor
Definition at line 524 of file mainloop_good.c.
References addclient(), clients, closeclient(), message(), MSG_ACCEPT, readecho(), and writeecho().
Referenced by main().
525 {
526     int             fd;
527     socklen_t       t;
528     struct sockaddr_in sain;
529 
530     t = sizeof(sain);
531     if ((fd = accept(clients[i].fd, (void *) &sain, &t)) == -1) {
532         if (errno == EWOULDBLOCK) {
533             return;
534         }
535         perror("accept(ECHO)");
536         exit(EXIT_FAILURE);
537     }
538     message(MSG_ACCEPT);
539     addclient(fd, &readecho, &writeecho, &closeclient);
540 }
void addalarm (alarmhandler_t handler, long interval) [static]
add new alarm
Parameters:
handler alarm handler procedure
interval interval in seconds
Bug no error handling, if there are no more error handler slots, the new alarm is ignored...
Definition at line 263 of file mainloop_good.c.
References alarmhandler(), alarms, alarm_t::flag, alarm_t::handler, alarm_t::interval, MAXALARMS, and alarm_t::nexttime.
Referenced by main().
264 {
265     struct timeval  now;
266     int             i;
267 
268     for (i = 0; i < MAXALARMS; i++) {
269         if (alarms[i].handler == NULL) {
270             gettimeofday(&now, NULL);
271             alarms[i].handler = handler;
272             alarms[i].interval = interval;
273             alarms[i].nexttime = now.tv_sec + interval;
274             alarms[i].flag = 0;
275             alarmhandler();
276             return;
277         }
278     }
279 }
void addclient (int fd, eventhandler_t read, eventhandler_t write, eventhandler_t except) [static]
add new client
Parameters:
fd file descriptor asociated with this client
read handler called if socket is readable
write handler called if socket is writable
except handler called on exceptions (HUP, close etc).
Definition at line 437 of file mainloop_good.c.
References clients, client_t::except, client_t::fd, MAXCLIENTS, message(), MSG_TOOMANY, npollfd, pollfds, client_t::read, and client_t::write.
Referenced by acceptchargen(), acceptecho(), and main().
439 {
440     if (npollfd >= (MAXCLIENTS - 1)) {
441         close(fd);
442         message(MSG_TOOMANY);
443         return;
444     }
445     clients[npollfd].fd = fd;
446     clients[npollfd].read = read;
447     clients[npollfd].write = write;
448     clients[npollfd].except = except;
449     pollfds[npollfd].fd = fd;
450     pollfds[npollfd].events = 0;
451     if (read) {
452         pollfds[npollfd].events |= POLLIN;
453     }
454     if (write) {
455         pollfds[npollfd].events |= POLLOUT;
456     }
457     npollfd++;
458 }
void alarmhandler (void) [static]
signal handler for alarms
mark expired alarms for execution and set new alarm timer.
the resolution of the alarm timer is one second, no attempt is made to get timing beyond this one second resolution (any sub-second timing information is discarded).
Definition at line 307 of file mainloop_good.c.
References alarms, alarm_t::flag, alarm_t::handler, alarm_t::interval, MAX, MAXALARMS, MIN, and alarm_t::nexttime.
Referenced by addalarm(), and initalarms().
308 {
309     struct timeval  now;
310     long            nextalarm;
311     int             i;
312 
313     gettimeofday(&now, NULL);
314 
315     nextalarm = 65536;
316     for (i = 0; i < MAXALARMS; i++) {
317         if (alarms[i].handler != NULL) {
318             if (alarms[i].nexttime <= now.tv_sec) {
319                 alarms[i].flag = 1;
320                 alarms[i].nexttime += alarms[i].interval;
321             }
322             nextalarm =
323                 MIN(nextalarm,
324                     MAX(1,
325                         (unsigned int) alarms[i].nexttime - now.tv_sec));
326         }
327     }
328     alarm((unsigned int) nextalarm);
329 }
void blocksigpipe (void) [static]
block SIGPIPE
Trying to write to a socket when the other end has already closed the connection results in SIGPIPE. Not usefull in this context.
Definition at line 214 of file mainloop_good.c.
215 {
216     struct sigaction act;
217 
218     act.sa_handler = SIG_IGN;
219     sigemptyset(&act.sa_mask);
220     act.sa_flags = SA_RESTART;
221     if (sigaction(SIGPIPE, &act, NULL) == -1) {
222         perror("sigaction(SIGPIPE, <ignore>)");
223         exit(EXIT_FAILURE);
224     }
225 }
void checkalarms (void) [static]
check for pending alarms and execute alarm handlers
Definition at line 285 of file mainloop_good.c.
References alarms, alarm_t::flag, alarm_t::handler, and MAXALARMS.
Referenced by mainloop().
286 {
287     int             i;
288 
289     for (i = 0; i < MAXALARMS; i++) {
290         if (alarms[i].flag) {
291             (*alarms[i].handler) ();
292             alarms[i].flag = 0;
293         }
294     }
295 }
void closeclient (int i) [static]
close and delete client session
Parameters:
i index into pollfds/clients array
Definition at line 666 of file mainloop_good.c.
References clients, delclient(), client_t::fd, message(), and MSG_CLOSE.
Referenced by acceptchargen(), acceptecho(), readecho(), writechargen(), and writeecho().
667 {
668     message(MSG_CLOSE);
669     close(clients[i].fd);
670     delclient(i);
671     clients[i].fd = -1;
672 }
void delclient (int i) [static]
delete client
Parameters:
i index into pollfds/clients array
Definition at line 466 of file mainloop_good.c.
References clients, client_t::fd, npollfd, and pollfds.
Referenced by closeclient().
467 {
468     clients[i].fd = -1;
469     if (i != npollfd) {
470         /* just copy the whole thing including the buffer... */
471         memcpy(&clients[i], &clients[npollfd], sizeof(clients[i]));
472         pollfds[i] = pollfds[npollfd];
473         npollfd--;
474     }
475 }
void flowecho (int i) [static]
do `flow` control for echo
Parameters:
i index into pollfds/clients array for echo session
turn off checking for read if buffer is full resp. write if buffer is empty.
Definition at line 646 of file mainloop_good.c.
References BUFSIZE, clients, client_t::echo, echo_client_t::n, and pollfds.
Referenced by readecho(), and writeecho().
647 {
648     switch (clients[i].echo.n) {
649     case 0:
650         pollfds[i].events = POLLIN;
651         break;
652     case BUFSIZE:
653         pollfds[i].events = POLLOUT;
654         break;
655     default:
656         pollfds[i].events = POLLIN | POLLOUT;
657     }
658 }
void heartbeat (void) [static]
print heartbeat message
Definition at line 335 of file mainloop_good.c.
References message(), and MSG_HEARTBEAT.
Referenced by main().
336 {
337     message(MSG_HEARTBEAT);
338 }
void initalarms (void) [static]
install non-resetting signal handler for alarms
The sigaction interface allows installing non-resetting signal handlers (ie not reset to SIG_DFL after disposition). This way, there is no race condition when reinstalling the signal handler.
Definition at line 235 of file mainloop_good.c.
References alarmhandler(), alarms, alarm_t::handler, and MAXALARMS.
Referenced by main().
236 {
237     struct sigaction act;
238     int             i;
239 
240     act.sa_handler = alarmhandler;
241     sigemptyset(&act.sa_mask);
242     act.sa_flags = 0;           /* no SIG_RESTART! */
243     if (sigaction(SIGALRM, &act, NULL) == -1) {
244         perror("sigaction(SIGPIPE, <ignore>)");
245         exit(EXIT_FAILURE);
246     }
247     for (i = 0; i < MAXALARMS; i++) {
248         alarms[i].handler = NULL;
249     }
250     alarm(0);                   /* cancel any previously made alarm request */
251 }
void initclients () [static]
initialize client state array
Definition at line 418 of file mainloop_good.c.
References clients, client_t::fd, MAXCLIENTS, and npollfd.
Referenced by main().
419 {
420     int             i;
421 
422     for (i = 0; i < MAXCLIENTS; i++) {
423         clients[i].fd = -1;
424     }
425     npollfd = 0;
426 }
int listensocket (int port) [static]
return tcp socket listening on port specified
Parameters:
port port number in host byte order
Returns: file descriptor for listening socket
The socket is set to be nonblocking
Definition at line 359 of file mainloop_good.c.
References setnonblock().
Referenced by listensource(), and main().
360 {
361     int             serverfd;
362     struct sockaddr_in sain;
363     int             one;
364 
365     /* set up tcp socket for listening */
366     sain.sin_family = AF_INET;
367     sain.sin_port = htons(port);
368     sain.sin_addr.s_addr = INADDR_ANY;
369     if ((serverfd = socket(AF_INET, SOCK_STREAM, 0)) == -1) {
370         perror("socket(AF_INET, SOCK_STREAM, 0)");
371         exit(EXIT_FAILURE);
372     }
373     one = 1;
374     if (setsockopt
375         (serverfd, SOL_SOCKET, SO_REUSEADDR, &one,
376          (int) sizeof(one)) == -1) {
377         perror("setsockopt(SO_REUSEADDR)");
378         exit(EXIT_FAILURE);
379     }
380     if (bind
381         (serverfd, (struct sockaddr *) &sain, sizeof(struct sockaddr_in))
382         == -1) {
383         perror("bind()");
384         exit(EXIT_FAILURE);
385     }
386     if (listen(serverfd, 5) == -1) {
387         perror("listen()");
388         exit(EXIT_FAILURE);
389     }
390     setnonblock(serverfd);
391 
392     printf("listening on port %d\n", port);
393 
394     return serverfd;
395 }
int main ()
Definition at line 734 of file mainloop_good.c.
References acceptchargen(), acceptecho(), addalarm(), addclient(), blocksigpipe(), heartbeat(), HEARTBEAT_INTERVAL, initalarms(), initclients(), listensocket(), mainloop(), PORT_CHARGEN, PORT_ECHO, slowheartbeat(), and SLOWHEARTBEAT_INTERVAL.
735 {
736     printf("example: better main loop\n");
737 
738     blocksigpipe();
739 
740     initclients();
741     addclient(listensocket(PORT_ECHO), &acceptecho, NULL, NULL);
742     addclient(listensocket(PORT_CHARGEN), &acceptchargen, NULL, NULL);
743     initalarms();
744     addalarm(heartbeat, HEARTBEAT_INTERVAL);
745     addalarm(slowheartbeat, SLOWHEARTBEAT_INTERVAL);
746     printf("heartbeat every %d seconds\n", HEARTBEAT_INTERVAL);
747     printf("slow heartbeat every %d seconds\n", SLOWHEARTBEAT_INTERVAL);
748 
749     /* main loop */
750     while (1) {
751         mainloop();
752     }
753     /* notreached */
754 }
void mainloop () [static]
execute one iteration of THE mainloop
Definition at line 481 of file mainloop_good.c.
References checkalarms(), clients, client_t::except, message(), MSG_MAINLOOP, npollfd, pollfds, client_t::read, and client_t::write.
Referenced by main().
482 {
483     int             i;
484 
485     message(MSG_MAINLOOP);
486     i = poll(pollfds, npollfd, -1);
487 
488     /* check for alarm handlers to be executed */
489     checkalarms();
490 
491     if (i == -1) {
492         if ((errno != EAGAIN) && (errno != EINTR)) {
493             perror("poll()");
494             exit(EXIT_FAILURE);
495         }
496         return;
497     }
498 
499     /* 
500      * handle i/o events. work off exceptions first. then read (try to fill
501      * buffer) and write (try to empty buffer)
502      */
503     for (i = 0; i <= npollfd; i++) {
504         if ((clients[i].except)
505             && (pollfds[i].revents & (POLLERR | POLLHUP | POLLNVAL))) {
506             (*clients[i].except) (i);
507             continue;
508         }
509         if ((clients[i].read) && (pollfds[i].revents & POLLIN)) {
510             (*clients[i].read) (i);
511         }
512         if ((clients[i].write) && (pollfds[i].revents & POLLOUT)) {
513             (*clients[i].write) (i);
514         }
515     }
516 }
void message (int msg) [static]
print message describing current activity
Parameters:
msg id of message to print (MSG_XYZ)
Definition at line 170 of file mainloop_good.c.
References MSG_ACCEPT, MSG_CLOSE, MSG_EMPTY, MSG_FULL, MSG_HEARTBEAT, MSG_MAINLOOP, MSG_READ, MSG_SLOWHEARTBEAT, MSG_TOOMANY, and MSG_WRITE.
Referenced by accept_dispatch(), acceptecho(), addclient(), chargen_dispatch(), closeclient(), echo_dispatch_read(), echo_dispatch_write(), heartbeat(), main(), mainloop(), readecho(), sighandler(), slowheartbeat(), source_close(), writechargen(), and writeecho().
171 {
172     switch (msg) {
173     case MSG_HEARTBEAT:
174         printf("H");
175         break;
176     case MSG_SLOWHEARTBEAT:
177         printf("S");
178         break;
179     case MSG_MAINLOOP:
180         /* printf("M"); */
181         break;
182     case MSG_ACCEPT:
183         printf("A");
184         break;
185     case MSG_TOOMANY:
186         printf("T");
187         break;
188     case MSG_CLOSE:
189         printf("C");
190         break;
191     case MSG_READ:
192         printf("R");
193         break;
194     case MSG_WRITE:
195         printf("W");
196         break;
197     case MSG_FULL:
198         printf("F");
199         break;
200     case MSG_EMPTY:
201         printf("E");
202         break;
203     }
204     fflush(stdout);
205 }
void readecho (int i) [static]
read data from echo client
Parameters:
i index into pollfds/clients array for echo session
If the buffer is not full, tries to do one read from the filedescriptor associated with this echo client.
Definition at line 551 of file mainloop_good.c.
References BUFSIZE, clients, closeclient(), client_t::echo, flowecho(), message(), MSG_FULL, MSG_READ, echo_client_t::n, echo_client_t::r, and echo_client_t::w.
Referenced by acceptecho(), and main().
552 {
553     ssize_t         nread;
554 
555     if (clients[i].echo.n == BUFSIZE) {
556         message(MSG_FULL);
557         flowecho(i);
558         return;
559     }
560     if (clients[i].echo.r >= clients[i].echo.w) {
561         nread =
562             read(clients[i].fd, clients[i].echo.buf + clients[i].echo.r,
563                  BUFSIZE - clients[i].echo.r);
564     } else {
565         nread =
566             read(clients[i].fd, clients[i].echo.buf + clients[i].echo.r,
567                  clients[i].echo.w - clients[i].echo.r);
568     }
569 
570     switch (nread) {
571     case -1:
572         if ((errno != EINTR) && (errno != EWOULDBLOCK)) {
573             perror("read()");
574             exit(EXIT_FAILURE);
575         }
576         break;
577     case 0:
578         closeclient(i);
579         return;
580     default:
581         message(MSG_READ);
582         clients[i].echo.n += nread;
583         clients[i].echo.r += nread;
584         clients[i].echo.r %= BUFSIZE;
585         flowecho(i);
586     }
587 }
void setnonblock (int fd) [static]
set a file descriptor to be nonblocking
Parameters:
fd file descriptor
Non-Blocking works only for Sockets, Pipes and slow devices, it has no effect when used with regular files or `fast` devices.
Definition at line 406 of file mainloop_good.c.
Referenced by accept_dispatch(), listensocket(), and main().
407 {
408     int             flag;
409 
410     flag = fcntl(fd, F_GETFL);
411     fcntl(fd, F_GETFL, flag | O_NONBLOCK);
412 }
void slowheartbeat (void) [static]
print `slowheartbeat` message
Definition at line 344 of file mainloop_good.c.
References message(), and MSG_SLOWHEARTBEAT.
Referenced by main().
345 {
346     message(MSG_SLOWHEARTBEAT);
347 }
void writechargen (int i) [static]
write data to an chargen client
Parameters:
i index into pollfds/clients array for chargen session
If the buffer is not empty, tries to do one write to the filedescriptor associated with the chargen client.
Definition at line 706 of file mainloop_good.c.
References client_t::chargen, chargen_buf, clients, closeclient(), chargen_client_t::i, message(), and MSG_WRITE.
Referenced by acceptchargen(), and main().
707 {
708     ssize_t         nwrite;
709 
710     nwrite =
711         write(clients[i].fd, chargen_buf + clients[i].chargen.i,
712               sizeof(chargen_buf) - clients[i].chargen.i);
713 
714     switch (nwrite) {
715     case -1:
716         if (errno == EPIPE) {
717             closeclient(i);
718             return;
719         } else if ((errno != EINTR) && (errno != EWOULDBLOCK)) {
720             perror("write()");
721             exit(EXIT_FAILURE);
722         }
723         break;
724     case 0:
725         break;
726     default:
727         message(MSG_WRITE);
728         clients[i].chargen.i += nwrite;
729         clients[i].chargen.i %= sizeof(chargen_buf);
730     }
731 }
void writeecho (int i) [static]
write data to an echo client
Parameters:
i index into pollfds/clients array for echo session
If the buffer is not empty, tries to do one write to the filedescriptor associated with the echo client.
Definition at line 598 of file mainloop_good.c.
References BUFSIZE, clients, closeclient(), client_t::echo, flowecho(), message(), MSG_EMPTY, MSG_WRITE, echo_client_t::n, echo_client_t::r, and echo_client_t::w.
Referenced by acceptecho(), and main().
599 {
600     ssize_t         nwrite;
601 
602     if (clients[i].echo.n == 0) {
603         message(MSG_EMPTY);
604         flowecho(i);
605         return;
606     }
607     if (clients[i].echo.r > clients[i].echo.w) {
608         nwrite =
609             write(clients[i].fd, clients[i].echo.buf + clients[i].echo.w,
610                   clients[i].echo.r - clients[i].echo.w);
611     } else {
612         nwrite =
613             write(clients[i].fd, clients[i].echo.buf + clients[i].echo.w,
614                   BUFSIZE - clients[i].echo.w);
615     }
616 
617     switch (nwrite) {
618     case -1:
619         if (errno == EPIPE) {
620             closeclient(i);
621         } else if ((errno != EINTR) && (errno != EWOULDBLOCK)) {
622             perror("write()");
623             exit(EXIT_FAILURE);
624         }
625         break;
626     case 0:
627         break;
628     default:
629         message(MSG_WRITE);
630         clients[i].echo.n -= nwrite;
631         clients[i].echo.w += nwrite;
632         clients[i].echo.w %= BUFSIZE;
633         flowecho(i);
634     }
635 }
Variable Documentation
alarm_t alarms[MAXALARMS] [static]
alarms
Definition at line 134 of file mainloop_good.c.
Referenced by addalarm(), alarmhandler(), checkalarms(), and initalarms().
char chargen_buf[] = `0123456789abcdefghijklmnopqrstuv` [static]
characters to return in chargen service
Definition at line 60 of file mainloop_good.c.
Referenced by writechargen().
client_t clients[MAXCLIENTS] [static]
array of client states
Definition at line 132 of file mainloop_good.c.
Referenced by acceptchargen(), acceptecho(), addclient(), closeclient(), delclient(), flowecho(), initclients(), mainloop(), readecho(), writechargen(), and writeecho().
unsigned long npollfd [static]
number of file descriptors to check
this is not as bad as it sounds because there's a static array for the struct pollfd anyway (pollfds). using an array for the client states allows using the same index for pollfds and clients.
in a real application, the buffer would be bigger, and therefore wouldn't be placed into the array ;) for demonstration purposes, the buffer is small to make it more interesting
Definition at line 131 of file mainloop_good.c.
Referenced by addclient(), delclient(), initclients(), and mainloop().
struct pollfd pollfds[MAXCLIENTS] [static]
pollfds for poll()
Definition at line 133 of file mainloop_good.c.
Referenced by addclient(), delclient(), flowecho(), and mainloop().